services:
  variflex:
    build:
      context: ./orchestrator
    image: variflex:latest
    container_name: variflex
    restart: unless-stopped
    ports:
      - "6002:6002"
    volumes:
      - variflex-data:/data
    environment:
      - TASK_RUNNER_RUNNERS=${TASK_RUNNER_RUNNERS}
      - TASK_RUNNER_REPOS=${TASK_RUNNER_REPOS}
      - TASK_RUNNER_DOCKHAND_URL=${TASK_RUNNER_DOCKHAND_URL}
      - TASK_RUNNER_DOCKHAND_TOKEN=${TASK_RUNNER_DOCKHAND_TOKEN}
      - TASK_RUNNER_DOCKHAND_ENV=${TASK_RUNNER_DOCKHAND_ENV}
      - TASK_RUNNER_RUNNER_IMAGE=${TASK_RUNNER_RUNNER_IMAGE}
      - TASK_RUNNER_RUNNER_AUTH_VOLUME=${TASK_RUNNER_RUNNER_AUTH_VOLUME}
      - TASK_RUNNER_RUNNER_NETWORK=${TASK_RUNNER_RUNNER_NETWORK}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FORGEJO_TOKEN=${FORGEJO_TOKEN}

volumes:
  variflex-data:
    external: true
    name: variflex-dev_variflex-data
